import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
const CONTROL=(process.env.CONTROL_PLANE_URL||'').replace(/\/$/,'');
const TOKEN=process.env.SESSION_TOKEN||'';
const DEVICE_ID=process.env.DEVICE_ID||`home-${os.hostname().replace(/[^A-Za-z0-9_-]/g,'-')}`;
const DEVICE_NAME=process.env.DEVICE_NAME||os.hostname();
const ROOT=path.resolve(process.env.WORKSPACE_ROOT||process.cwd());
const MOCK=process.env.MOCK_CODEX==='1';
if(!CONTROL){console.error('CONTROL_PLANE_URL is required');process.exit(1)}
if(!/^[A-Za-z0-9_-]{40,128}$/.test(TOKEN)){console.error('SESSION_TOKEN is invalid');process.exit(1)}
const H={authorization:`Bearer ${TOKEN}`,'content-type':'application/json'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function api(p,b){const r=await fetch(`${CONTROL}${p}`,{method:b===undefined?'GET':'POST',headers:H,body:b===undefined?undefined:JSON.stringify(b)});if(!r.ok)throw new Error(`${r.status} ${p}: ${await r.text()}`);return r.json()}
async function progress(id,type,text){return api(`/api/task/${id}/event`,{deviceId:DEVICE_ID,type,text})}
async function heartbeat(){return api('/api/device/heartbeat',{deviceId:DEVICE_ID,name:DEVICE_NAME,platform:`${process.platform}/${process.arch}`,capabilities:['codex','filesystem','git','shell'],workspace:ROOT})}
function summary(item){if(!item||typeof item!=='object')return null;if(item.type==='agent_message'&&item.text)return ['assistant',item.text.slice(0,480)];if(item.type==='command_execution')return ['command',item.command||'command'];if(item.type==='file_change')return ['file',item.path||'file changed'];if(item.type==='mcp_tool_call')return ['tool',item.tool||item.name||'tool call'];return null}
async function runMock(task){await progress(task.id,'planning','依頼を整理しています');await sleep(700);await progress(task.id,'working','Home Server 上で作業しています');await sleep(900);await progress(task.id,'verification','結果を確認しています');await sleep(650);return{result:`Home Worker の接続試験結果です。\n\n受領した依頼: ${task.prompt}`,threadId:`mock-${task.id}`}}
async function runCodex(task){const {Codex}=await import('@openai/codex-sdk');const codex=new Codex();const options={workingDirectory:ROOT,skipGitRepoCheck:true,sandboxMode:'workspace-write',approvalPolicy:'never',networkAccessEnabled:true};if(task.routing?.model&&task.routing.model!=='auto')options.model=task.routing.model;if(task.routing?.effort&&task.routing.effort!=='auto')options.modelReasoningEffort=task.routing.effort;const thread=codex.startThread(options);const prompt=`You are the execution worker behind a personal agent. Execute the user's task inside the configured workspace. Use files, git, tests, and tools when relevant. Do not wait for conversational confirmation for ordinary reversible work. Finish with a concise Japanese report of what you did, what changed, tests/checks, and anything that remains.\n\nUSER TASK:\n${task.prompt}`;const {events}=await thread.runStreamed(prompt);let finalResponse='',usage=null,lastPush=0;for await(const e of events){if(e.type==='item.completed'){if(e.item?.type==='agent_message'&&e.item.text)finalResponse=e.item.text;const s=summary(e.item);if(s&&Date.now()-lastPush>300){const ack=await progress(task.id,s[0],s[1]);lastPush=Date.now();if(ack.cancelRequested)throw new Error('Task cancellation requested')}}else if(e.type==='turn.completed')usage=e.usage||null;else if(e.type==='turn.failed')throw new Error(e.error?.message||'Codex turn failed');else if(e.type==='error')throw new Error(e.message||'Codex stream error')}return{result:finalResponse||'Codex の処理が終了しました。',threadId:thread.id,usage}}
async function execute(task){console.log(`[task] ${task.id} ${task.title}`);await progress(task.id,'accepted',`${DEVICE_NAME} が受理しました`);try{const out=MOCK?await runMock(task):await runCodex(task);await api(`/api/task/${task.id}/complete`,{deviceId:DEVICE_ID,...out});console.log(`[done] ${task.id}`)}catch(e){const m=e instanceof Error?e.message:String(e);await api(`/api/task/${task.id}/fail`,{deviceId:DEVICE_ID,error:m}).catch(()=>{});console.error(`[failed] ${task.id}: ${m}`)}}
async function main(){console.log(`Personal Agent Home Worker\ncontrol=${CONTROL}\ndevice=${DEVICE_NAME}\nworkspace=${ROOT}\ncodex=${MOCK?'mock':'real'}`);let hb=0;for(;;){try{if(Date.now()-hb>10000){await heartbeat();hb=Date.now()}const {task}=await api('/api/worker/poll',{deviceId:DEVICE_ID});if(task)await execute(task)}catch(e){console.error(`[loop] ${e instanceof Error?e.message:String(e)}`)}await sleep(1500)}}
main();
